title: Jake Parente # your name (or website title) here
logo: "/images/cropped.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Enthusiastic programmer eager to contribute to team success through hard work, attention to detail and
  excellent organizational skills. Clear understanding of software development. Motivated to learn, grow
  and excel.<br>
  Graduated from the University of Calgary in 2020 with a BSc in Computer Science.
  <br><br>
  Prospective Software Developer.
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
