title: Jake Parente # your name (or website title) here
logo: "/images/cropped.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduated from the University of Calgary in 2020 with a BSc in Computer Science.
  <br><br>
  Prospective Software Developer.
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
